---
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(rvest)
library(xml2)
library(pdftools)
library(tidyverse)
library(magrittr)
library(gghighlight)
library(DT)
library(plotly)

source("function_niid.R", encoding = "CP932")

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

```

```{r update_data}
# update data -------------------------------------------------------------
 source("niid.R")
# 
# df <- read_csv("data.csv")

# now_week <- get_new_week() %>% str_remove("^.*-")
# now_date <- df %>% 
#   filter(week == now_week, year == date() %>% str_sub(-4, str_length(.))) %>% 
#   pull(date) %>% .[1]
# 

```

[感染研HP](https://www.niid.go.jp/niid/ja/data.html "https://www.niid.go.jp/niid/ja/data.html")のデータを使用した。

## 2012からの定点観測データ
```{r show_data}
datatable(df, extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


## 2012からの定点当たり報告数
拡大・縮小、年の選択等の変更が可能です。

```{r plotly, fig.width=8}
plot_ly(df %>% filter(prefecture == "総数"), x = ~week, y = ~fixed_point, color = ~year %>% as.factor,
        type = "scatter", mode = "lines+markers", 
        colors = gg_color_hue(df$year %>% unique %>% length)) 


```

## 2017年からの定点当たり報告数
```{r}
df %>% filter(prefecture == "総数", year > 2016) %>%
  ggplot(aes(week, fixed_point, colour = as.factor(year))) +
  geom_line(aes(group = year), size = 1) +
  geom_point() + 
  ylab("定点当たり報告数") +
  gghighlight() +
  facet_grid(rows = vars(year))
```


## 2021~2023シーズンの報告者数
```{r, fig.width=12}

df %>% filter(prefecture == "総数") %>% 
  filter(between(year, 2021, 2023)) %>% 
  ggplot(aes(week, number, colour = as.factor(year))) +
  geom_line(aes(group = year), size = 1) +
  geom_point() +
  theme(
    legend.title = element_blank()
  )
```

## `r get_new_week()`週の定点当たり報告数

```{r pref}
japan02 <- df %>% dplyr::filter(year == !!now_year, week == !!now_week %>% as.integer) %>% 
  filter(prefecture != "総数") %>% 
  mutate(Pref = 1:47)
japan01 %>% 
  left_join(japan02, by = "Pref") %>% 
  ggplot() + 
  geom_sf(aes(fill = fixed_point)) + 
  theme_void() + 
  scale_fill_continuous(low = "#FFFFFF", 
                        high = "#0000FF",
                        name = "定点当たり報告数")

```




```{r shiny}
# sliderInput(
#   "Xaxis", label = "Select x axis",
#   min = 2012, max = 2022, 
#   value = c(2012, 2022)
# )
# checkboxGroupInput(
#   "year", label = "Select year", 
#   choices = 2012:2022, 
#   selected = 2017:2022
# )
# 
# renderPlot({
#   df %>% filter(prefecture == "総数", year %in% as.integer(input$year)) %>%
#   ggplot(aes(week, number, colour = as.factor(year))) +
#   geom_line(aes(group = year), size = 1) +
#   geom_point() + 
#   gghighlight() +
#   coord_cartesian(xlim = as.integer(input$Xaxis)) +
#   facet_grid(rows = vars(year))
# })

```


---
title: "インフルエンザ感染状況 (`r get_new_week()`週`r now_date`) "
---